# Generated by Django 4.2.13 on 2026-06-05 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='recepcion.habitacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='recepcion.hotel'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.huesped'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='recepcion.tipohabitacion'),
        ),
        migrations.AddField(
            model_name='folio',
            name='estancia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='reservas.estancia'),
        ),
        migrations.AddField(
            model_name='estancia',
            name='atendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estancias_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estancia',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='recepcion.habitacion'),
        ),
        migrations.AddField(
            model_name='estancia',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estancia', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='estancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='reservas.estancia'),
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
