# Generated by Django 4.2.13 on 2026-07-02 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huesped', to=settings.AUTH_USER_MODEL),
        ),
    ]
