# Generated by Django 4.2.13 on 2026-07-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_huesped_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='usuario',
        ),
    ]
