# Generated by Django 4.2.13 on 2026-07-12 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0002_tipohabitacion_imagen_imagentipohabitacion'),
        ('reservas', '0005_huesped_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargoestancia',
            options={'ordering': ['fecha'], 'verbose_name': 'Cargo de Estancia', 'verbose_name_plural': 'Cargos de Estancia'},
        ),
        migrations.AlterModelOptions(
            name='estancia',
            options={'verbose_name': 'Estancia', 'verbose_name_plural': 'Estancias'},
        ),
        migrations.AlterModelOptions(
            name='folio',
            options={'verbose_name': 'Folio', 'verbose_name_plural': 'Folios'},
        ),
        migrations.RemoveField(
            model_name='estancia',
            name='precio_final',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='igv',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='cargoestancia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='estancia',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='estancia',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='estancia',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='estancia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='folio',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='folio',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='folio',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='folio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='cargoestancia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargoestancia',
            name='tipo',
            field=models.CharField(choices=[('HABITACION', 'Habitación'), ('RESTAURANTE', 'Restaurante'), ('MINIBAR', 'Minibar'), ('LAVANDERIA', 'Lavandería'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estancias', to='recepcion.habitacion'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('PAGADO', 'Pagado'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='folio',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('YAPE', 'Yape'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='nacionalidad',
            field=models.CharField(default='Peruana', max_length=50),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='tipo_doc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=3),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.huesped'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_adultos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_ninos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='origen',
            field=models.CharField(choices=[('WEB', 'Web'), ('DIRECTO', 'Directo'), ('AGENCIA', 'Agencia')], default='DIRECTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='recepcion.tipohabitacion'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
