# Generated by Django 4.2.13 on 2026-07-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_cargoestancia_options_alter_estancia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='acepta_emails',
            field=models.BooleanField(default=False),
        ),
    ]
