# Generated by Django 4.2.13 on 2026-07-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0005_alter_opcioncheckin_options'),
        ('reservas', '0007_huesped_acepta_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='opcion_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_checkin', to='recepcion.opcioncheckin'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='opcion_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_checkout', to='recepcion.opcioncheckin'),
        ),
    ]
