# Generated by Django 4.2.13 on 2026-07-16 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0003_habitacion_activo_habitacion_actualizado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en')),
                ('tipo', models.CharField(choices=[('CHECKIN', 'Early Check-in'), ('CHECKOUT', 'Late Check-out')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.TimeField()),
                ('cargo_extra', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_checkin', to='recepcion.hotel')),
            ],
            options={
                'verbose_name': 'Opción Check-in/out',
                'verbose_name_plural': 'Opciones Check-in/out',
                'ordering': ['tipo', 'hora'],
            },
        ),
    ]
