# Generated by Django 4.2.13 on 2026-07-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_opcioncheckin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcioncheckin',
            options={'ordering': ['tipo', 'cargo_extra', 'hora'], 'verbose_name': 'Opción Check-in/out', 'verbose_name_plural': 'Opciones Check-in/out'},
        ),
    ]
