# Generated by Django 4.2.13 on 2026-06-05 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housekeeping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarealimpieza',
            name='asignada_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_limpieza', to='recepcion.habitacion'),
        ),
        migrations.AddField(
            model_name='incidentehabitacion',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='recepcion.habitacion'),
        ),
        migrations.AddField(
            model_name='incidentehabitacion',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
