# Generated by Django 4.2.13 on 2026-07-12 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentehabitacion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='incidentehabitacion',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='incidentehabitacion',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='incidentehabitacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='tarealimpieza',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
