# Generated by Django 4.2.13 on 2026-07-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0003_incidentehabitacion_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarealimpieza',
            name='tipo',
            field=models.CharField(choices=[('LIMPIEZA', 'Limpieza'), ('REVISION', 'Revisión pre-checkout')], default='LIMPIEZA', max_length=10),
        ),
    ]
