# Generated by Django 4.2.13 on 2026-07-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_opcion_checkin_reserva_opcion_checkout'),
        ('housekeeping', '0004_tarealimpieza_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarealimpieza',
            name='estancia_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_housekeeping', to='reservas.estancia'),
        ),
    ]
