# Generated by Django 4.2.13 on 2026-06-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('recepcionista', 'Recepcionista'), ('housekeeping', 'Housekeeping'), ('cliente', 'Cliente')], default='recepcionista', max_length=20),
        ),
    ]
