# Generated by Django 4.2.13 on 2026-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('recepcionista', 'Recepcionista'), ('housekeeping', 'Housekeeping')], default='recepcionista', max_length=20),
        ),
    ]
